/* tslint:disable */
/* eslint-disable */
export const drop_pk: (a: number) => void;
export const link_verify: (a: number, b: number, c: number, d: number) => [number, number, number];
export const load_pk: (a: number, b: number, c: number) => [number, number];
export const load_pk_begin: (a: number, b: number, c: number) => [number, number];
export const load_pk_cancel: (a: number) => void;
export const load_pk_chunk: (a: number, b: number, c: number) => [number, number];
export const load_pk_finish: (a: number) => [number, number];
export const prove: (a: number, b: number, c: number) => [number, number, number];
export const verify: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasm_init: () => void;
export const build_split_inputs: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: any, l: number, m: number, n: number, o: number) => [number, number, number];
export const cert_modulus_bits: (a: number, b: number) => [number, number, number];
export const cert_serial_hex: (a: number, b: number) => [number, number, number, number];
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const initThreadPool: (a: number) => any;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
